version: "3.9"

services:
  backend:
    build: ./backend
    container_name: todo-backend-test
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: test
    restart: always

  frontend:
    build: ./frontend
    container_name: todo-frontend-test
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always
