# Nom du workflow tel qu’il apparaît dans GitHub Actions
name: Production

# =========================
# Déclencheur du workflow
# =========================
on:
  # workflow_dispatch permet un déclenchement MANUEL
  # Le déploiement en production n’est donc jamais automatique
  workflow_dispatch:

jobs:
  # =========================
  # Job de déploiement PROD
  # =========================
  frontend:
    # Nom lisible du job affiché dans l’interface GitHub Actions
    name: Frontend - Audit, Lint & Tests

    # Type de machine virtuelle utilisée pour exécuter le job
    runs-on: ubuntu-latest

    # Configuration par défaut pour toutes les commandes `run`
    defaults:
      run:
        # Tous les `run:` seront exécutés dans le dossier frontend/
        # → évite de répéter le chemin à chaque étape
        working-directory: frontend

    # Liste des étapes exécutées dans l’ordre
    steps:
      # Étape 1 : récupérer (cloner) le dépôt GitHub
      - name: Checkout repository
        # Action officielle GitHub pour cloner le repo
        uses: actions/checkout@v5

      # Étape 2 : installer Node.js et configurer npm
      - name: Setup node
        # Action officielle pour installer Node.js
        uses: actions/setup-node@v4
        with:
          # Version de Node.js utilisée par le frontend
          node-version: 22

          # Active le cache automatique des dépendances npm
          # accélère les exécutions suivantes du CI
          cache: npm

          # Chemin vers le package-lock.json utilisé pour le cache
          # nécessaire car le projet est dans frontend/
          cache-dependency-path: frontend/package-lock.json

      # Étape 3 : installation propre des dépendances
      - name: Install dependencies
        # npm ci est optimisé pour les environnements CI
        # installation rapide et reproductible
        run: npm ci

      - name: Build
        run: npm run build:only

      # Création de l'artifact (Upload) pour les tests
      - uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: frontend/dist

  deploy-production:
    # Nom du job affiché dans GitHub Actions
    name: Deploy production

    # Le job s’exécute sur une VM Linux fournie par GitHub
    runs-on: ubuntu-latest

    # Ce job ne démarre QUE si le job "build" a réussi
    # → garantit que seul un code validé est déployé
    needs: build

    steps:
      # 1. Récupération du code
      - name: Checkout repository
        # Clone le dépôt GitHub sur le runner
        # Nécessaire pour accéder aux fichiers (.github/actions/vpn, etc.)
        uses: actions/checkout@v5

        # Téléchargement de l'Artifact
      - name: Download artifact
        use: actions/download-artifact@v4
        with:
          name: artifact
          path: dist

      # 2. Connexion au VPN
      - name: VPN setup
        # Utilise l’action VPN fournie par l’enseignant
        # Elle installe openconnect et établit le tunnel VPN
        uses: ./.github/actions/vpn
        with:
          # Adresse du serveur VPN Fortinet
          host: ${{ secrets.VPN_HOST }}

          # Port du VPN (souvent 443)
          port: ${{ secrets.VPN_PORT }}

          # Identifiant VPN
          username: ${{ secrets.VPN_USERNAME }}

          # Mot de passe VPN (stocké en secret)
          password: ${{ secrets.VPN_PASS }}

          # IP interne à pinguer pour vérifier que le VPN fonctionne
          # Ici : la VM TEST
          ping_host: ${{ secrets.TEST_HOST_IP }}

      # 3. Déploiement sur la VM TEST
      - name: Copy files SSH (SCP)
        # Action permettant d’exécuter des commandes SSH sur un serveur distant
        uses: appleboy/scp-action@v1
        with:
          # Adresse IP de la VM TEST (accessible UNIQUEMENT via VPN)
          host: ${{ secrets.TEST_HOST_IP }}

          # Utilisateur SSH
          username: ${{ secrets.TEST_SSH_USER }}

          # Mot de passe SSH (fourni par l’enseignant)
          password: ${{ secrets.TEST_SSH_PASS }}

          # Port SSH
          port: ${{ secrets.SSH_PORT }}

          source: "./frontend/dist,/backend,docker-compose.yaml"
          target: ~/todo-app2

      # Tout s'éxécute sur la VM maintenant
      - name: SSH commands
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.TEST_HOST_IP }}
          username: ${{ secrets.TEST_USERNAME }}
          password: ${{ secrets.TEST_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/todo-app2/backend
            echo 'DB_URL="${{ secrets.DB_URL }}"' > .env
            cd ~/todo-app2
            docker compose up -d
            cd ~/todo-app2/backend
            npm run start:prod
            pm2 save
